#!/bin/sh

echo "# Installing yadm"
mkdir -p "$HOME/.local/bin"
curl -fLo "$HOME/.local/bin/yadm" \
	https://github.com/TheLocehiliosan/yadm/raw/master/yadm
chmod a+x "$HOME/.local/bin/yadm"
export PATH="$HOME/.local/bin:$PATH"

echo "# Cloning the repo"
yadm clone https://github.com/nblagoev/env.git --bootstrap
yadm submodule update --init --recursive
